version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging into ECR
            - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 816470285182.dkr.ecr.eu-west-1.amazonaws.com
    build:
        commands:
            - echo Building Docker Image...
            - docker build -t paul_counter .
            - docker tag paul_counter:latest 816470285182.dkr.ecr.eu-west-1.amazonaws.com/paul_counter:latest
    post_build:
        commands:
            - echo Pushing Docker image to ECR...
            - docker push 816470285182.dkr.ecr.eu-west-1.amazonaws.com/paul_counter:latest
            #- echo Creating imagedefinitions.json
            #- printf '[{"name": "counter", "imageUri": "%s"}]' 816470285182.dkr.ecr.eu-west-1.amazonaws.com/paul_counter:latest > imagedefinitions.json

artifacts:
    files:
        - '**/*'
        #- imagedefinitions.json
