version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging into ECR
            - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 022499048865.dkr.ecr.eu-central-1.amazonaws.com
    build:
        commands:
            - echo Building Docker Image...
            - docker build -t paul-counter-new .
            - docker tag paul-counter-new:latest 022499048865.dkr.ecr.eu-central-1.amazonaws.com/paul-counter-new:latest
    post_build:
        commands:
            - echo Pushing Docker image to ECR...
            - docker push 022499048865.dkr.ecr.eu-central-1.amazonaws.com/paul-counter-new:latest
            - echo Creating imagedefinitions.json
            - printf '[{"name": "counter", "imageUri": "%s"}]' 022499048865.dkr.ecr.eu-central-1.amazonaws.com/paul-counter-new:latest > imagedefinitions.json

artifacts:
    files:
        - '**/*'
        - imagedefinitions.json
